kind: Service
apiVersion: v1
metadata:
  name: mongo-service
  labels: 
    app: mongo
spec:
  selector:
    app: mongo
    #tier: backend
  ports:
    - protocol: TCP
      port: 27017
      targetPort: mongoport