kind: Service
apiVersion: v1
metadata:
  name: api-service
  labels: 
    app: api
spec:
  selector:
    app: api
    #tier: backend
  ports:
     - port: 4567 #inside pod port
       protocol: TCP
       name: apiport
  type: NodePort